service: ft-twist

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  deploymentBucket: ${env:AWS_DEPLOYMENT_BUCKET_PREFIX}
  role: ${env:AWS_ROLE}
  runtime: nodejs6.10

functions:
  gtg:
    handler: functions/gtg.handler
    events:
      - http:
          path: /__gtg
          method: get
  home:
    handler: functions/home.handler
    events:
      - http:
          path: /
          method: get
  triggerWebpagetest:
    handler: functions/trigger-webpagetest.handler
    events:
      - http:
          path: /trigger-webpagetest
          method: get
      - schedule: rate(12 hours)
    environment:
      WEBPAGETEST_API_KEY: ${env:WEBPAGETEST_API_KEY}
  receiveWebpagetest:
    handler: functions/receive-webpagetest.handler
    events:
      - http:
          path: /receive-webpagetest
          method: get
    environment:
      SLACK_WEBHOOK: ${env:SLACK_WEBHOOK}


package:
  individually: true
