service: ft-twist

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  deploymentBucket: ${env:AWS_DEPLOYMENT_BUCKET_PREFIX}
  role: ${env:AWS_ROLE}
  runtime: nodejs6.10
  memorySize: 128
  timeout: 120
  versionFunctions: false
  stackTags: # Note these don't get applied to existing lambda functions, only new ones
    environment: p
    systemCode: twist
    teamDL: next.team@ft.com

functions:
  gtg:
    handler: functions/gtg.handler
    events:
      - http:
          path: /__gtg
          method: get
  home:
    handler: functions/home.handler
    events:
      - http:
          path: /
          method: get
  triggerWebpagetest:
    handler: functions/trigger-webpagetest.handler
    events:
      - http:
          path: /trigger-webpagetest
          method: get
      - schedule: rate(12 hours)
    environment:
      WEBPAGETEST_API_KEY: ${env:WEBPAGETEST_API_KEY}
  receiveWebpagetest:
    handler: functions/receive-webpagetest.handler
    events:
      - http:
          path: /receive-webpagetest
          method: get
    environment:
      SLACK_WEBHOOK: ${env:SLACK_WEBHOOK}
      SPLUNK_HEC_TOKEN: ${env:SPLUNK_HEC_TOKEN}
      SPLUNK_HEC_URL: ${env:SPLUNK_HEC_URL}
      SPLUNK_LOG_LEVEL: ${env:SPLUNK_LOG_LEVEL}

package:
  individually: true
  exclude:
    - ./**
  include:
    - node_modules/**
    - package.json
